version: '3.8'
services:
  db:
    container_name: smoothie-database
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=smoothie
    ports:
      - '5432:5432'

  backend:
    container_name: smoothie-backend
    build:
      context: ./smoothie_backend
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=jdbc:postgresql://smoothie-database:5432/smoothie
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./smoothie-frontend
      dockerfile: ./Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend